DAILY_PRODUCT_DICT = {
    "ClaveProducto": None,
    "ClaveSubProducto": None,
    "ReporteDeVolumenMensual": None,
    "ComposOctanajeGasolina": None,
    "GasolinaConCombustibleNoFosil": None,
    "ComposDeCombustibleNoFosilEnGasolina": None,
    "DieselConCombustibleNoFosil": None,
    "ComposDeCombustibleNoFosilEnDiesel": None,
    "TurbosinaConCombustibleNoFosil": None,
    "ComposDeCombustibleNoFosilEnTurbosina": None,
    "ComposDePropanoEnGasLP": None,
    "ComposDeButanoEnGasLP": None,
    "DensidadDePetroleo": None,
    "ComposDeAzufreEnPetroleo": None,
    "Otros": None,
    "MarcaComercial": None,
    "Marcaje": None,
    "ConcentracionSustanciaMarcaje": None,
    "GasNaturalOCondensados": None,
    "Tanque": None,
    "Ducto": None,
    "Pozo": None,
    "Dispensario": None
    }

MONTHLY_PRODUCT_DICT = {
    "ClaveProducto": None,
    "ClaveSubProducto": None,
    "ReporteDeVolumenMensual": None,
    "ComposOctanajeGasolina": None,
    "GasolinaConCombustibleNoFosil": None,
    "ComposDeCombustibleNoFosilEnGasolina": None,
    "DieselConCombustibleNoFosil": None,
    "ComposDeCombustibleNoFosilEnDiesel": None,
    "TurbosinaConCombustibleNoFosil": None,
    "ComposDeCombustibleNoFosilEnTurbosina": None,
    "ComposDePropanoEnGasLP": None,
    "ComposDeButanoEnGasLP": None,
    "DensidadDePetroleo": None,
    "ComposDeAzufreEnPetroleo": None,
    "Otros": None,
    "MarcaComercial": None,
    "Marcaje": None,
    "ConcentracionSustanciaMarcaje": None,
    "GasNaturalOCondensados": None,
    }
