from .cfdi import Cfdi
from .permiso import Permiso
from .archivo import Archivo
from .bitacora import Bitacora
from .certificado import Certificado
from .manguera import Manguera
from .pedimento import Pedimento
from .producto import Producto
from .tanque import Tanque
from .composicion import Composicion
from .ducto import Ducto
from .existencia_d_tanque import ExistenciaDTanque
from .existencia_m_tanque import ExistenciaMTanque
from .medidor_dispensario import MedidorDispensario
from .medidor_ducto import MedidorDucto
from .medidor_tanque import MedidorTanque
from .movimiento_ducto import MovimientoDucto
from .movimiento_tanque import MovimientoTanque
from .dictamen import Dictamen
from .dispensario import Dispensario
from .movimiento_dispensario import MovimientoDispensario